# Generated by Django 5.0.7 on 2024-08-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_projeto_data_criacao_projeto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='responsavel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
